### ISSUE TITLE
 v0.12.1 crashes upon startup

### ISSUE THREAD

**Issue by pserwylo** [beat-feet/beat-feet#106]
Specifically with `UnsatisfiedLinkError: ... couldn't find "libgdx.so"`

This is due to a bump in the gradle version and gradle plugin version. I attempted to fix it in v0.12.1 but obviously have not succeeded. For reference:
* [Discussion on the Unciv issue tracker](https://github.com/yairm210/Unciv/issues/3946#issuecomment-857474194).
* [Fix from the Unciv team](https://github.com/yairm210/Unciv/pull/4090/files)
* [Same issue on retrowars](https://github.com/retrowars/retrowars/issues/25)
* [Fix for retrowars](https://github.com/retrowars/retrowars/commit/27dc3573d0cecf3fd57f3b63272e41351a3f1b74)

This is the logcat error from Beat Feet:

```
07-14 06:57:34.954 22700 22700 E AndroidRuntime: FATAL EXCEPTION: main
07-14 06:57:34.954 22700 22700 E AndroidRuntime: Process: com.serwylo.beatgame, PID: 22700
07-14 06:57:34.954 22700 22700 E AndroidRuntime: java.lang.ExceptionInInitializerError
07-14 06:57:34.954 22700 22700 E AndroidRuntime: 	at java.lang.Class.newInstance(Native Method)
07-14 06:57:34.954 22700 22700 E AndroidRuntime: 	at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
07-14 06:57:34.954 22700 22700 E AndroidRuntime: 	at android.app.Instrumentation.newActivity(Instrumentation.java:1264)
07-14 06:57:34.954 22700 22700 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3797)
07-14 06:57:34.954 22700 22700 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4077)
07-14 06:57:34.954 22700 22700 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
07-14 06:57:34.954 22700 22700 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
07-14 06:57:34.954 22700 22700 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
07-14 06:57:34.954 22700 22700 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2458)
07-14 06:57:34.954 22700 22700 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:110)
07-14 06:57:34.954 22700 22700 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:219)
07-14 06:57:34.954 22700 22700 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8387)
07-14 06:57:34.954 22700 22700 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-14 06:57:34.954 22700 22700 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
07-14 06:57:34.954 22700 22700 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
07-14 06:57:34.954 22700 22700 E AndroidRuntime: Caused by: com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load shared library 'gdx' for target: Linux, 32-bit
07-14 06:57:34.954 22700 22700 E AndroidRuntime: 	at com.badlogic.gdx.utils.SharedLibraryLoader.load(SharedLibraryLoader.java:126)
07-14 06:57:34.954 22700 22700 E AndroidRuntime: 	at com.badlogic.gdx.utils.GdxNativesLoader.load(GdxNativesLoader.java:31)
07-14 06:57:34.954 22700 22700 E AndroidRuntime: 	at com.badlogic.gdx.backends.android.AndroidApplication.<clinit>(AndroidApplication.java:44)
07-14 06:57:34.954 22700 22700 E AndroidRuntime: 	... 15 more
07-14 06:57:34.954 22700 22700 E AndroidRuntime: Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.serwylo.beatgame-0mWSTSF-c2Ly2L-RJdNrfg==/base.apk"],nativeLibraryDirectories=[/data/app/com.serwylo.beatgame-0mWSTSF-c2Ly2L-RJdNrfg==/lib/arm64, /system/lib64, /hw_product/lib64, /system/product/lib64, /prets/lib64]]] couldn't find "libgdx.so"
07-14 06:57:34.954 22700 22700 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
07-14 06:57:34.954 22700 22700 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
07-14 06:57:34.954 22700 22700 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1668)
07-14 06:57:34.954 22700 22700 E AndroidRuntime: 	at com.badlogic.gdx.utils.SharedLibraryLoader.load(SharedLibraryLoader.java:120)
07-14 06:57:34.954 22700 22700 E AndroidRuntime: 	... 17 more
```

**Comment by pserwylo** [comment]
Oh gosh, here is the "fix": https://github.com/beat-feet/beat-feet/commit/512a22c9e163b9d78a0c09409083d8dbaf4e474d#diff-197b190e4a3512994d2cebed8aff5479ff88e136b8cc7a4b148ec9c3945bd65aR64-R69

All it does is add a comment, not actually patch the issue [like it should have](https://github.com/retrowars/retrowars/commit/27dc3573d0cecf3fd57f3b63272e41351a3f1b74#diff-197b190e4a3512994d2cebed8aff5479ff88e136b8cc7a4b148ec9c3945bd65aR75).
